### ISSUE TITLE
KMIA

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Navigation#426]
Data for all runways modified. Runways 12/30 and 09/27 moved (both with ILS as well 08R and 26L).

**Comment by CptNathanHope** [comment]
All fixed up! :)

**Comment by zhf21** [comment]
All ILSes will need modifications due to an airport rework performed in 2019. 

**LOC RWY 8L:** https://aeronav.faa.gov/d-tpp/2109/00257L8L.PDF
**ILS OR LOC RWY 8R:** https://aeronav.faa.gov/d-tpp/2109/00257IL8R.PDF
**ILS OR LOC RWY 9:** https://aeronav.faa.gov/d-tpp/2109/00257IL9.PDF
**ILS OR LOC RWY 12:** https://aeronav.faa.gov/d-tpp/2109/00257IL12.PDF
**ILS OR LOC RWY 26L:** https://aeronav.faa.gov/d-tpp/2109/00257IL26L.PDF
**LOC RWY 26R:** https://aeronav.faa.gov/d-tpp/2109/00257L26R.PDF
**ILS OR LOC RWY 27:** https://aeronav.faa.gov/d-tpp/2109/00257IL27.PDF
**ILS OR LOC RWY 30:** https://aeronav.faa.gov/d-tpp/2109/00257IL30.PDF
