### ISSUE TITLE
KPSM

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Navigation#595]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**ILS equipped:**
Runway 16
Runway 34

**Comment by CptNathanHope** [comment]
Fixed in [`dc0df1d`](https://github.com/InfiniteFlightAirportEditing/Navigation/commit/dc0df1d3abbebcd16c2ed5d54b262a68e8e077d9).

**Comment by zhf21** [comment]
This airport was edited almost one year after these ILSes were added. If possible, could this issue be re-opened? The latitude and longitude need to be adjusted accordingly. It is not a big change, but since I have a PR open with room for more fixes, I don't see an issue. :)

Change in coordinates for reference:

<img width="215" alt="Screen Shot 2021-05-09 at 1 16 14 PM" src="https://user-images.githubusercontent.com/67797012/117581036-bd407d00-b0c8-11eb-918a-099bca16d76d.png">

<img width="221" alt="Screen Shot 2021-05-09 at 1 16 44 PM" src="https://user-images.githubusercontent.com/67797012/117581052-ce898980-b0c8-11eb-9c34-e50c2ecb6512.png">
